POST http://localhost:3001/api/blogs
Content-Type: application/json

{
  "title": "Blogin lisääjäksi tulee järjestyksessä ensimmäinen käyttäjä kannassa",
  "author": "Samu Sirkka",
  "url": "http://samu.example.com/",
  "likes": 100
}